//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace SpotHunt
{
		public class Player {
			int danger = 5;
			int x = -1;
			int y = -1;
			Playfield playfield;
			
			/**
	 * The player constructor.
	 * @param playfield the <code>Playfield</code> the player is playing on.
	 */
			public Player(Playfield playfield) {
				this.playfield = playfield;
			}
			
			/**
	 * <code>getDangerLevel</code> returns the danger level of the player.
	 * @return danger
	 */
			public int getDangerLevel() {
				return danger;
			}
			
			/**
	 * <code>setLocation</code> moves the Player to a new location, given an <code>x</code> and <code>y</code>.
	 * @param newX	the new x coordinate of the player.
	 * @param newY	the new y coordinate of the player.
	 */
			public void setLocation(int newX, int newY) {
				// Update cells
				if(x!=-1 && y!=-1) playfield.cells[x][y].removePlayer();
				x = newX;
				y = newY;
				playfield.cells[x][y].putPlayer();
			}
			
			/**
	 * <code>getX</code> returns the x coordinate of the player.
	 * @return x
	 */
			public int getX() {
				return x;
			}
			
			/**
	 * <code>getY</code> returns the y coordinate of the player.
	 * @return y
	 */
			public int getY() {
				return y;
			}
			
			/**
	 * <code>toString</code> overwrites the default <code>toString()</code> method.
	 * @return [x,y]
	 */
			public String toString() {
				return "[" + this.x + "," + this.y + "]";
			}
		}
}

