//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public interface Spot
		{
		/**
	 	* <code>setLocation</code> moves the <code>MovingSpot</code> to a new location, given an <code>x</code> and <code>y</code>.
	 	* @param newX	the new x coordinate of the spot.
	 	* @param newY	the new y coordinate of the spot.
	 	*/
		void setLocation(int newX, int newY);
		
		/**
	 	* <code>getX</code> returns the x coordinate of the spot.
	 	* @return x
	 	*/
		int getX();
		
		/**
	 	* <code>getY</code> returns the y coordinate of the spot.
	 	* @return y
	 	*/
		int getY();
		
		/**
	 	* <code>toString</code> overwrites the default <code>toString()</code> method.
	 	* @return [x,y]
	 	*/
		String toString();
		}
}

